.TH sdss 1 "03.04.2021" "CUR_VERSION"
.SH NAME
sdss \- stow dotfiles setup script
.SH SYNOPSIS
.B sdss
.I command
.I args
.SH DESCRIPTION
.PP
.B sdss
is a tool to manage the deployment of dotfiles with the use of GNU stow.
The dotfiles are organized into packages inside of
.I git
repos and packages/repos can be activated/deactivated individually.
.B sdss
also handles switching file versions and encrypting passwords and such.
.SH ARGUMENTS
.B sdss
takes exactly one
.I command
and the appropriate amount of arguments for the given
.I command
\&.
.SH COMMANDS
.TP
.BR [\-c, " " \-\-clone] " " \fIREPO\fR
Clone a repo into the repo directory.
.TP
.BR [\-a, " " \-\-activate\-package] " " \fIREPO\fR " " \fIPACKAGE\fR
Activate a single package.
.TP
.BR [\-A, " " \-\-activate\-repo] " " \fIREPO\fR
Activate all packages inside of this repo.
.TP
.BR [\-d, " " \-\-deactivate\-package] " " \fIREPO\fR " " \fIPACKAGE\fR
Deactivate a single package.
.TP
.BR [\-D, " " \-\-deactivate\-repo] " " \fIREPO\fR
Deactivate all packages inside of this repo.
.TP
.BR [\-l, " " \-\-list\-packages] " " \fIREPO\fR
List all packages inside of this repo. TODO: Also displays active status.
.TP
.BR [\-L, " " \-\-list\-repos]
List all Repos.
.TP
.BR [\-R, " " \-\-refresh]
Refreshes the deployment version of all packages. Selects appropriate file
versions and applies patches in the
.I sdss.secret
file.
.TP
.BR [\-V, " " \-\-change\-version] " " \fIVERSION\fR
Changes currently deployed file versions. Does not apply changes until manually
refreshed with
.BR \-R
command.
.TP
.BR [\-f, " " \-\-get\-repos\-location]
Returns the folder that contains all
.B sdss
repos.
.TP
.BR [\-F, " " \-\-get\-package\-location] " " \fIREPO\fR " " \fIPACKAGE\fR
Get the working folder of given package.
.SH DETAILS
.PP
All persistent configuration of
.B sdss
is handled via the environment variables
.I SDSS_DATA_DIR
and
.I SDSS_DEST_DIR
\&.
.PP
.I SDSS_DATA_DIR
controls where
.B sdss
stores all of the repos and packages. The standard value of
.I SDSS_DATA_DIR
is
.B ${XDG_DATA_HOME:-$HOME/.local/share}/sdss
\&.
.PP
.I SDSS_DEST_DIR
controls where
.B sdss
deploys dotfiles to. The standard value of
.I SDSS_DEST_DIR
is
.B $HOME
\&.
.PP
The file layout inside of is detailed in
.BR \%sdss (5)
\&.
.PP
.B sdss
can also handle multiple versions of the same file and deploy them based on the
currently active version as selected by the
.BR \-V
command. The naming scheme used to handle versioned files is detailed in
.BR \%sdss (5)
\&.
.PP
.B sdss
can also handle storing data like passwords and API keys inside of a GPG
encrypted file and inserting the encrypted data into the deployed files.
.B sdss
also handles the GPG en\-/decryption of the secret file. The layout of the file
containing all the encrypted data is detailed in
.BR \%sdss (5)
\&.
